version: "3.8"
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: yarn start:dev
    ports:
      - "3300:3300"
    environment:
      NODE_ENV: development
